### ISSUE TITLE
Rules: state clearly that all the work made is to be documented

### ISSUE THREAD

**Issue by Vovcick** [vbonvin/IPT-public#17] opened 2016-08-08 11:20 UTC
I disliked very much this year some presentations where the participants have said that they have made experiments or calculations but didn't include it into presentation. Some of them couldn't even say a word about the setup they used.
Let us say somewhere:
"All the work made should be documented and even if not included into the main part it should be shown after the correpsonding questions. In case it is not documented or it is not shown after the request it is considered to be a pure fiction."

As for me it's rather obvious but as for the participants and juries it may be not. Also it will increase motivation to prepare the problem well.

**Comment by Vovcick** [comment] 2016-08-08 11:30
Also we may think about proper ways of documentation for experiments made, theoretical calculations or computer modelling.
For the first type it may be photo or video of the working experimental setup. Maybe we may even say that every experimental point should have the documentation but maybe we may consider this surplus.
For the second type it may be separate slides with all the calculations in details.
For the third one it may be the program code and numerical results in form of tables or plots or even in some graphical form.
In any case I feel the discussion on this topic may be useful.

**Comment by vbonvin** [comment] 2016-08-08 11:58
This is a duplicate of issue #7. I'm moving your comments there and closing this issue.

**Closed by vbonvin** 2016-08-08 11:58 UTC
Labels: enhancement, rules
