### ISSUE TITLE
Establish a way to choose problems for the preselection

### ISSUE THREAD

**Issue by LVoronina** [vbonvin/IPT-public#9] opened 2016-08-02 14:55 UTC
We need to decide how we choose the problems for the preselection.  

**Suggestion:**  
Simple vote inside the execom, 3 problems, all in different branches of physics. Before voting - a Skype meeting to discuss pros and cons, to be better informed.  When we will have the depository of problems with the comments, there will be no need to do that.

The deadline to be stated in the rules.

**Comment by vbonvin** [comment] 2016-08-02 15:12
> Simple vote inside the execom, 3 problems, all in different branches of physics. Before voting - a Skype meeting to discuss pros and cons, to be better informed. When we will have the depository of problems with the comments, there will be no need to do that.

Sounds good to me. 

We can also ask people from the IOC to suggest problems by writing directly to us, but without giving them any feedback about it.

We need also to be careful when communicating about it. What if some countries ask in advance to know which problems will be in the pre-selection, but do not organize a national selection in the end ? Do we minor their pre-selection grade somehow, e.g. multiplying the final grade by 0.8 ? Or do we count on their good faith ? Let's discuss this in issue #10 :)

> The deadline to be stated in the rules.

I'd say that we can have up to two weeks after the problem selection for the IOC members to suggest problems, then one additional week to decide into the execom which problems do we choose. Then, we agree to communicate these three problems since the start of the semester (say October 1st) to the IOC members that ask for it ?

**Comment by Vovcick** [comment] 2016-08-03 15:45
Look very nice :-)
Let us say that Vivien will ask all the IOC to propose three problems of the approximately equal level of difficulty and of different physical fields. Surely after that we should discuss the problems and to make our decision on them. And if we meet in more or less big makeup we don't need in more or less big this vote as we can select the problems during the meeting. Also a good point would be that the problem is better if it can be solved in a simple way for poor points and in a very hard and challenging way for good points. As for me, such problems will be the most precious for the preselection.

**Comment by vbonvin** [comment] 2016-08-05 11:18
> Also a good point would be that the problem is better if it can be solved in a simple way for poor points and in a very hard and challenging way for good points.

Well, in theory this should be the case for all the problems... but I agree, if we can find three problems like this for the preselection that would be great

**Comment by vbonvin** [comment] 2016-08-10 15:44
This joins the discussion #10. Closing

**Closed by vbonvin** 2016-08-10 15:44 UTC
Labels: problems, rules
